/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * AI Job Match Assistant
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

export interface AnalyzeRequest {
  resume?: string | null;
  resume_url?: string | null;
  vacancy?: string | null;
  vacancy_url?: string | null;
  mode?: string;
}

export interface ResumeItem {
  candidate_id: string;
  resume: string;
}

export interface BatchRequest {
  vacancy: string;
  resumes: ResumeItem[];
}

export interface CandidateResult {
  candidate_id: string;
  match_score: number;
  decision: string;
  seniority: string;
  skills_found: string[];
  skills_missing: string[];
  explanation: string;
}

export interface BatchResponse {
  results: CandidateResult[];
}

export interface BodyParseResumeApiParseResumePost {
  file: Blob;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  status: string;
  version: string;
}

export type ParseResumeApiParseResumePost200 = {[key: string]: string};

export type healthHealthGetResponse200 = {
  data: HealthResponse
  status: 200
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health
 */
export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {

  const res = await fetch(getHealthHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthHealthGetResponse
}




export const getHealthHealthGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError,void, TContext> => {

const mutationKey = ['healthHealthGet'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthHealthGet>>, void> = () => {


          return  healthHealthGet(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthHealthGetMutationResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>

    export type HealthHealthGetMutationError = unknown

    /**
 * @summary Health
 */
export const useHealthHealthGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthHealthGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthHealthGetMutationOptions(options), queryClient);
    }

export type analyzeApiAnalyzePostResponse200 = {
  data: unknown
  status: 200
}

export type analyzeApiAnalyzePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type analyzeApiAnalyzePostResponseSuccess = (analyzeApiAnalyzePostResponse200) & {
  headers: Headers;
};
export type analyzeApiAnalyzePostResponseError = (analyzeApiAnalyzePostResponse422) & {
  headers: Headers;
};

export type analyzeApiAnalyzePostResponse = (analyzeApiAnalyzePostResponseSuccess | analyzeApiAnalyzePostResponseError)

export const getAnalyzeApiAnalyzePostUrl = () => {




  return `/api/analyze`
}

/**
 * @summary Analyze
 */
export const analyzeApiAnalyzePost = async (analyzeRequest: AnalyzeRequest, options?: RequestInit): Promise<analyzeApiAnalyzePostResponse> => {

  const res = await fetch(getAnalyzeApiAnalyzePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(analyzeRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: analyzeApiAnalyzePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as analyzeApiAnalyzePostResponse
}




export const getAnalyzeApiAnalyzePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeApiAnalyzePost>>, TError,{data: AnalyzeRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof analyzeApiAnalyzePost>>, TError,{data: AnalyzeRequest}, TContext> => {

const mutationKey = ['analyzeApiAnalyzePost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof analyzeApiAnalyzePost>>, {data: AnalyzeRequest}> = (props) => {
          const {data} = props ?? {};

          return  analyzeApiAnalyzePost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AnalyzeApiAnalyzePostMutationResult = NonNullable<Awaited<ReturnType<typeof analyzeApiAnalyzePost>>>
    export type AnalyzeApiAnalyzePostMutationBody = AnalyzeRequest
    export type AnalyzeApiAnalyzePostMutationError = HTTPValidationError

    /**
 * @summary Analyze
 */
export const useAnalyzeApiAnalyzePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeApiAnalyzePost>>, TError,{data: AnalyzeRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof analyzeApiAnalyzePost>>,
        TError,
        {data: AnalyzeRequest},
        TContext
      > => {
      return useMutation(getAnalyzeApiAnalyzePostMutationOptions(options), queryClient);
    }

export type batchAnalyzeApiBatchPostResponse200 = {
  data: BatchResponse
  status: 200
}

export type batchAnalyzeApiBatchPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type batchAnalyzeApiBatchPostResponseSuccess = (batchAnalyzeApiBatchPostResponse200) & {
  headers: Headers;
};
export type batchAnalyzeApiBatchPostResponseError = (batchAnalyzeApiBatchPostResponse422) & {
  headers: Headers;
};

export type batchAnalyzeApiBatchPostResponse = (batchAnalyzeApiBatchPostResponseSuccess | batchAnalyzeApiBatchPostResponseError)

export const getBatchAnalyzeApiBatchPostUrl = () => {




  return `/api/batch`
}

/**
 * @summary Batch Analyze
 */
export const batchAnalyzeApiBatchPost = async (batchRequest: BatchRequest, options?: RequestInit): Promise<batchAnalyzeApiBatchPostResponse> => {

  const res = await fetch(getBatchAnalyzeApiBatchPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(batchRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: batchAnalyzeApiBatchPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as batchAnalyzeApiBatchPostResponse
}




export const getBatchAnalyzeApiBatchPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchAnalyzeApiBatchPost>>, TError,{data: BatchRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof batchAnalyzeApiBatchPost>>, TError,{data: BatchRequest}, TContext> => {

const mutationKey = ['batchAnalyzeApiBatchPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchAnalyzeApiBatchPost>>, {data: BatchRequest}> = (props) => {
          const {data} = props ?? {};

          return  batchAnalyzeApiBatchPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BatchAnalyzeApiBatchPostMutationResult = NonNullable<Awaited<ReturnType<typeof batchAnalyzeApiBatchPost>>>
    export type BatchAnalyzeApiBatchPostMutationBody = BatchRequest
    export type BatchAnalyzeApiBatchPostMutationError = HTTPValidationError

    /**
 * @summary Batch Analyze
 */
export const useBatchAnalyzeApiBatchPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchAnalyzeApiBatchPost>>, TError,{data: BatchRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchAnalyzeApiBatchPost>>,
        TError,
        {data: BatchRequest},
        TContext
      > => {
      return useMutation(getBatchAnalyzeApiBatchPostMutationOptions(options), queryClient);
    }

export type parseResumeApiParseResumePostResponse200 = {
  data: ParseResumeApiParseResumePost200
  status: 200
}

export type parseResumeApiParseResumePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type parseResumeApiParseResumePostResponseSuccess = (parseResumeApiParseResumePostResponse200) & {
  headers: Headers;
};
export type parseResumeApiParseResumePostResponseError = (parseResumeApiParseResumePostResponse422) & {
  headers: Headers;
};

export type parseResumeApiParseResumePostResponse = (parseResumeApiParseResumePostResponseSuccess | parseResumeApiParseResumePostResponseError)

export const getParseResumeApiParseResumePostUrl = () => {




  return `/api/parse-resume`
}

/**
 * @summary Parse Resume
 */
export const parseResumeApiParseResumePost = async (bodyParseResumeApiParseResumePost: BodyParseResumeApiParseResumePost, options?: RequestInit): Promise<parseResumeApiParseResumePostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyParseResumeApiParseResumePost.file);

  const res = await fetch(getParseResumeApiParseResumePostUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: parseResumeApiParseResumePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as parseResumeApiParseResumePostResponse
}




export const getParseResumeApiParseResumePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof parseResumeApiParseResumePost>>, TError,{data: BodyParseResumeApiParseResumePost}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof parseResumeApiParseResumePost>>, TError,{data: BodyParseResumeApiParseResumePost}, TContext> => {

const mutationKey = ['parseResumeApiParseResumePost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof parseResumeApiParseResumePost>>, {data: BodyParseResumeApiParseResumePost}> = (props) => {
          const {data} = props ?? {};

          return  parseResumeApiParseResumePost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ParseResumeApiParseResumePostMutationResult = NonNullable<Awaited<ReturnType<typeof parseResumeApiParseResumePost>>>
    export type ParseResumeApiParseResumePostMutationBody = BodyParseResumeApiParseResumePost
    export type ParseResumeApiParseResumePostMutationError = HTTPValidationError

    /**
 * @summary Parse Resume
 */
export const useParseResumeApiParseResumePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof parseResumeApiParseResumePost>>, TError,{data: BodyParseResumeApiParseResumePost}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof parseResumeApiParseResumePost>>,
        TError,
        {data: BodyParseResumeApiParseResumePost},
        TContext
      > => {
      return useMutation(getParseResumeApiParseResumePostMutationOptions(options), queryClient);
    }
