"""add resume_file_id to analysis

Revision ID: 40fa45ae75c9
Revises: d30c80467fd3
Create Date: 2026-05-28 21:35:53.247722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fa45ae75c9'
down_revision: Union[str, Sequence[str], None] = 'd30c80467fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('resume_file_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'resume_file_id')
    # ### end Alembic commands ###
